{% set version = "1.3.7" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-qdaptools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qdapTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qdapTools/qdapTools_{{ version }}.tar.gz
  sha256: 57ea66524f4e96dc5359e019974b76358202d9252450e901544241fc3b15c4b1

build:
  number: 2
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcurl
    - r-xml
    - r-chron
    - r-data.table >=1.9.6
  run:
    - r-base
    - r-rcurl
    - r-xml
    - r-chron
    - r-data.table >=1.9.6

test:
  commands:
    - $R -e "library('qdapTools')"           # [not win]
    - "\"%R%\" -e \"library('qdapTools')\""  # [win]

about:
  home: http://trinker.github.com/qdapTools/
  license: GPL-2.0-only
  summary: A collection of tools associated with the 'qdap' package that may be useful outside of the context of text analysis.
  license_family: GPL2
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
