{% set version = "1.3.5" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-qdaptools
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/qdapTools_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/qdapTools/qdapTools_{{ version }}.tar.gz
  sha256: 8c8828877ab63ad705b69e187c01d7c7098a88989bdde9e956ac559cc6de7e25

build:
  noarch: generic
  merge_build_host: true  # [win]
  number: 2
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcurl
    - r-xml
    - r-chron
    - r-data.table >=1.9.6
  run:
    - r-base
    - r-rcurl
    - r-xml
    - r-chron
    - r-data.table >=1.9.6

test:
  commands:
    - $R -e "library('qdapTools')"           # [not win]
    - "\"%R%\" -e \"library('qdapTools')\""  # [win]

about:
  home: http://trinker.github.com/qdapTools/
  license: GPL-2
  summary: A collection of tools associated with the 'qdap' package that may be useful outside of the context of text analysis.
  license_family: GPL2
  license_file: {{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2

extra:
  recipe-maintainers:
    - conda-forge/r
