appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: kZjcTNukdRjTS/iDfkJVdOEMG7ZbTDqZg9okwbNmBqSH4b+ot2ZM+q4e65urC8QRlt1CU19rNSF4N3SVm0+eOXdyyINwoS9yJgSgEVna3RbXYazCXdZGDJysfG684zeEx8tKg3+rNjqqIbyFnvuJiv0z9WfoNw8bUDNxg9Xe2GvECCphOQsZOhQ+h7HG+3AAD3an9Fo5M7NvcO4NAZ7BogVuEys9LxSyKGMPlcaQk7clIB1x0MmHuaNzBJTkcgVIJIBRW/Y0Qm9R63QOEgKEQ3GgNOwyqzpgufGu/KDTpo7KILl0acE6UOHFns3G/PJcyY6DF1HTHtH4um+Z80jx37sKobPVL3bHmprDhskGVqVKThUvXZW3cb9tu9kBn1lvUTlihaf4riUsV9NTVYjY5UJrTP7guxpoCrNt2LZ+wXX04oPFxuenSjQo6JLzrOxFY3PS0/AL5YnkrKPwWaWuI6lKB+cz47++oIhZ426Th63tgmRpKeAxNK0NqwYluYRVC8vRWI7cJhWa9KEpIVkzzYnYr+xgTCl+2FSZssxOC3THWQ3tqq6qXn2UzKt8ozPamtq6ekh3e+u7nb+9iFIRbBzVbU9WiM5U0zSBO7a43Z9AvL0dPnfmQAWeho2hl2+b8hhwYQWL0/Hg+9MkfKp13DoHlxtuTYDlHTlNVKS4fSI=}
bot:
  automerge: true
