travis:
  secure:
    BINSTAR_TOKEN: vkDkidzfwHE+KSxumN6vVNVJNPbHX01nIBMN66NSDC8lROWvmgI+zMQLmFxkRVAhWvxVAua2BKuo3oV7+uq0UDwXr4jD9PEtBUJWDoyIX3/7NE7V/4VV6uaNYx90Cpqn4D+nsdfdDQNEydMw94UPoFpBS05BaAwGZGVSBjFcx9ro4H4huExtGNuV6y+IuTwuWppi5wPhSVECmuHq6MCwe0ZZPApr/4gMpoV1/H9dja3jYaaLzL2zPHoVATtoapMTAcNIh8jDyaKj5Bsk79BhFZpzAtUlvic5uJvBOjF+RfLJqjpYdN1WkREb/vbGIcdM8JoZU1x1aNCIIbYZKr25DuPVmfgZTY7CYkDysXLixj08rnDeZPCv7SzGWRFwzqIdiNsF4gILyCHygeZ0kOPAF6+5ITzfl+k/jhI25qI2NdINWQmm9oCm/FcZd6ZAxawd8IYJLev25RzooFuqi0J9y7WjJPP8t4w0oazKhZtYiPOrb8c9gorLUu6VV1p0s1QQqRIQusFDJR/kytFbYUHI7Kovb6kYQOklvvi7t2nQsOHm8TNQUmTZ2hzePp0fDDB/5iY4hs4l0al9j96X3Dp/8MN3T/0x1LLyD8ITJ+L7T5fo6+dBde4URVHNz8GMSa6qkkA+1tQWbmac6gc0Q7jh5gju6t2wNHPmiO0PRK5bZas=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
